# Site settings
title: IJB Thinks
subtitle: JB's Idea Marketplace
email: ijbthinks@ijb.cisv.org
description: An online community of JBers around the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Daniel Krajnak

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"

# Social settings
facebook_url: https://www.facebook.com/ijb.cisv/
instagram_url: https://www.instagram.com/cisvofficial/
twitter_url: https://twitter.com/ijbnews


# Build settings
include: ["_categories"]
markdown: kramdown
sass:
  style: compressed
permalink: /:year/:month/:day/:title/

